const coverImage = [
    {"albumPic": "Taylor Swift",
     "coverPic": "https://upload.wikimedia.org/wikipedia/en/1/1f/Taylor_Swift_-_Taylor_Swift.png"},
    {"albumPic": "Fearless",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/8/86/Taylor_Swift_-_Fearless.png"},
    {"albumPic": "Speak Now",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/8/8f/Taylor_Swift_-_Speak_Now_cover.png"},
    {"albumPic": "Red",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/e/e8/Taylor_Swift_-_Red.png"},
    {"albumPic": "1989",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/f/f6/Taylor_Swift_-_1989.png"},
    {"albumPic": "Reputation",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/f/f2/Taylor_Swift_-_Reputation.png"},
    {"albumPic": "Lover",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/c/cd/Taylor_Swift_-_Lover.png"},
    {"albumPic": "Folklore",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/f/f8/Taylor_Swift_-_Folklore.png"},
    {"albumPic": "Evermore",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/0/0a/Taylor_Swift_-_Evermore.png"},
    {"albumPic": "Midnights",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/9/9f/Midnights_-_Taylor_Swift.png"},
    {"albumPic": "The Tortured Poets Department",
    "coverPic": "https://upload.wikimedia.org/wikipedia/en/6/6e/Taylor_Swift_%E2%80%93_The_Tortured_Poets_Department_%28album_cover%29.png"}
]